server:
  port: ${PORT:8085}

spring:
  application:
    name: payment-gateway
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payment_gateway}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
vault:
  master-key: ${VAULT_MASTER_KEY:}

jwt:
  secret-key: ${JWT_SECRET_KEY}

payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    methods:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      NETBANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95

