server:
  port: ${PORT:8085}

spring:
  application:
    name: payment-gateway
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payment_gateway}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
